---
- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - curl
          - git
          - tmux
          - vim
          - wget
          - zsh
        state: present
      become: yes

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | sh
      args:
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install oh-my-zsh
      command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: /home/{{ ansible_user_id }}/.oh-my-zsh

    - name: Install zsh syntax highlight
      command: git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
      args:
        chdir: /home/{{ ansible_user_id }}/.oh-my-zsh/zsh-syntax-highlighting

    - name: Install z
      get_url:
        url: https://raw.githubusercontent.com/rupa/z/master/z.sh
        dest: /home/{{ ansible_user_id }}

    - name: zshrc
      copy:
        src: ./templates/zshrc
        dest: /home/{{ ansible_user_id }}/.zshrc

    - name: Create vim themes path
      file:
        path: /home/{{ ansible_user_id }}/.vim/colors
        state: directory
    - name: Download vim monokay
      get_url:
        url: https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
        dest: /home/{{ ansible_user_id }}/.vim/colors

    - name: vimrc
      copy:
        src: ./templates/vimrc
        dest: /home/{{ ansible_user_id }}/.vimrc

    - name: tmux config
      copy:
        src: ./templates/tmux.conf
        dest: /home/{{ ansible_user_id }}/.tmux.conf
