---
- hosts: all
  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - curl
          - git
          - tmux
          - vim
          - wget
          - zsh
        state: present
      become: yes
    - name: Install nvm
      command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | /bin/bash
